apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: external-secrets-operator
    app.kubernetes.io/name: external-secrets-operator
    app.kubernetes.io/managed-by: kustomize
  name: deny-all-traffic
  namespace: system
spec:
  podSelector:
    matchLabels:
      app: external-secrets-operator
  policyTypes:
    - Ingress
    - Egress